import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./components/general/dark-mode/providers";
import { AppSidebar } from "./components/general/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Navigation } from "./components/general/navigation";

export const metadata: Metadata = {
    title: "POS - Services",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
                <head />
                <body>
                    <Providers>
                        <SidebarProvider>
                            <AppSidebar />
                            <main className="container px-8 py-8">
                                <div className="mb-8 flex items-center gap-4">
                                    <SidebarTrigger />
                                    <Navigation />
                                </div>
                                {children}
                            </main>
                        </SidebarProvider>
                    </Providers>
                </body>
            </html>
        </>
    );
}
