import type { Metadata } from "next";
import "./globals.css";
import { ModeToggle } from "./components/general/dark-mode/toggle";
import { Providers } from "./components/general/dark-mode/providers";

export const metadata: Metadata = {
  title: "POS - Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <Providers>
            <ModeToggle />
            {children}
          </Providers>
        </body>
      </html>
    </>
  );
}
