import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./components/general/dark-mode/providers";
import { AppSidebar } from "./components/general/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata: Metadata = {
    title: "POS - Services",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
                <head />
                <body>
                    <Providers>
                        <SidebarProvider>
                            <AppSidebar />
                            {children}
                        </SidebarProvider>
                    </Providers>
                </body>
            </html>
        </>
    );
}
